# Generated by Django 3.1 on 2020-08-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdeed_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quotes2',
        ),
        migrations.DeleteModel(
            name='quotes3',
        ),
    ]
