# Generated by Django 3.1 on 2020-08-12 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdeed_app', '0003_deeds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quotes',
        ),
    ]
