# Generated by Django 3.1 on 2020-08-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdeed_app', '0004_delete_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='deeds2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deed', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=80)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='deeds3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deed', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=80)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='deeds',
            new_name='deeds1',
        ),
    ]
