# Generated by Django 3.1 on 2021-02-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdeed_app', '0005_auto_20200813_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='globalLamrim2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deed', models.CharField(max_length=600)),
                ('name', models.CharField(max_length=80)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
