# Generated by Django 3.1 on 2022-02-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdeed_app', '0006_globallamrim2'),
    ]

    operations = [
        migrations.CreateModel(
            name='repentance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('full_prostration_counter', models.PositiveIntegerField(default=0)),
                ('half_prostration_counter', models.PositiveIntegerField(default=0)),
                ('bow_counter', models.PositiveIntegerField(default=0)),
                ('recitation_counter', models.PositiveIntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
