# Generated by Django 3.1 on 2022-02-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdeed_app', '0007_repentance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repentance',
            old_name='name',
            new_name='username',
        ),
    ]
