# Generated by Django 3.1 on 2022-02-28 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vdeed_app', '0009_auto_20220227_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='sutra_recitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahaprajnaparamita_sutra_counter', models.PositiveIntegerField(default=0)),
                ('heart_sutra_counter', models.PositiveIntegerField(default=0)),
                ('medicine_buddha_sutra_counter', models.PositiveIntegerField(default=0)),
                ('golden_light_sutra_counter', models.PositiveIntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mantra_recitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('om_mani_padme_hum_counter', models.PositiveIntegerField(default=0)),
                ('manjushri_mantra_counter', models.PositiveIntegerField(default=0)),
                ('green_tara_mantra_counter', models.PositiveIntegerField(default=0)),
                ('migtsema_counter', models.PositiveIntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
