# Generated by Django 3.1 on 2022-03-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdeed_app', '0010_mantra_recitation_sutra_recitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantra_recitation',
            name='green_tara_mantra_target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mantra_recitation',
            name='manjushri_mantra_target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mantra_recitation',
            name='migtsema_target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mantra_recitation',
            name='om_mani_padme_hum_target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repentance',
            name='bow_target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repentance',
            name='full_prostration_target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repentance',
            name='half_prostration_target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repentance',
            name='recitation_target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sutra_recitation',
            name='golden_light_sutra_target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sutra_recitation',
            name='heart_sutra_target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sutra_recitation',
            name='mahaprajnaparamita_sutra_target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sutra_recitation',
            name='medicine_buddha_sutra_target',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
