# Generated by Django 3.1 on 2022-03-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdeed_app', '0011_auto_20220303_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='counter_target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_prostration_target', models.PositiveIntegerField(default=0)),
                ('half_prostration_target', models.PositiveIntegerField(default=0)),
                ('bow_target', models.PositiveIntegerField(default=0)),
                ('recitation_target', models.PositiveIntegerField(default=0)),
                ('mahaprajnaparamita_sutra_target', models.PositiveIntegerField(default=0)),
                ('heart_sutra_target', models.PositiveIntegerField(default=0)),
                ('medicine_buddha_sutra_target', models.PositiveIntegerField(default=0)),
                ('golden_light_sutra_target', models.PositiveIntegerField(default=0)),
                ('om_mani_padme_hum_target', models.PositiveIntegerField(default=0)),
                ('manjushri_mantra_target', models.PositiveIntegerField(default=0)),
                ('green_tara_mantra_target', models.PositiveIntegerField(default=0)),
                ('migtsema_target', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
